<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>cf9be3ee-237f-4a4a-8a2d-1b2ee68f7178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>57e522c6-83cd-43c6-84b1-948cc915d59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6Ill3aVE2RnRMcUlhd3N6b0JXNWw0SHc9PSIsInZhbHVlIjoiMlBTOUMreFpON3VpRytrMmo2bEUxM09kZlR4RUhnbERiNXlkS25oSE1MTT0iLCJtYWMiOiJmOWQ1YzUwZDM4MjlhYzExNjY3MGE1NWQwM2FlYWZiMjAxNDM2Mjc5Yzk2ODU5OWY5Yzk0YTJkMjVkNDJkYTRmIiwidGFnIjoiIn0=</value>
      <webElementGuid>6cade16e-ea4d-4118-aa24-1ecb02edfaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79405fe8-b932-4fe3-8ea8-fdfa8b50e216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>b8d85997-d597-4354-87e2-ce201585b8f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>0c1857f5-be4e-497a-92a0-35e6556c6e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='has been successfully updated'])[1]/following::img[1]</value>
      <webElementGuid>78bd65f8-ef86-4d73-ae97-e2b626933129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='videoplayback'])[2]/following::img[1]</value>
      <webElementGuid>3c99ff96-df9d-4e45-92a8-b1ed65a8f856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::img[2]</value>
      <webElementGuid>ec3fb1d2-356c-47a5-b7d4-dd3a9dcc2f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::img[2]</value>
      <webElementGuid>716f1d90-d9c2-4c61-8e8e-0b255d3d8b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>c5c1212b-156a-4aba-9916-245698c6a61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>068333c5-db83-43ce-90d5-38c91df42dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6Ill3aVE2RnRMcUlhd3N6b0JXNWw0SHc9PSIsInZhbHVlIjoiMlBTOUMreFpON3VpRytrMmo2bEUxM09kZlR4RUhnbERiNXlkS25oSE1MTT0iLCJtYWMiOiJmOWQ1YzUwZDM4MjlhYzExNjY3MGE1NWQwM2FlYWZiMjAxNDM2Mjc5Yzk2ODU5OWY5Yzk0YTJkMjVkNDJkYTRmIiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>722e2272-7077-4057-8fc7-5f485b719fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
