<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>421d0e8e-145f-4222-99fd-6d519223b950</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd3c9638-e06f-4802-a58a-6ff581cb7fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6IkNENENDN1pmaGhsVGtmeUh5S1ZtQlE9PSIsInZhbHVlIjoiVkFaSlA4VHhkTUR6QUFGNG1vNWNUcldwWEVGTEZjSlBVQ1R2OVVmL0s4TT0iLCJtYWMiOiJmOTVkMGYwZjY1NTUzNDQ0NGFiYjkzMzg3OThmYWU4YzJkMzc3ZGVjNmI3ZmE2Nzk0NDcxYTlhYTQyMTYxYjIzIiwidGFnIjoiIn0=</value>
      <webElementGuid>6e9b9d5d-8ddf-411d-98b2-55b87947354f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cf13146b-8735-4501-9303-35fcc72108df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>f1abb1e4-2991-4a23-af41-14ff25fd4d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>d0ec2c74-0029-4bdd-b824-02fd96153f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='has been successfully updated'])[1]/following::img[1]</value>
      <webElementGuid>4309abcf-9dfc-4cd3-86bb-3237f3b9960e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='videoplayback'])[2]/following::img[1]</value>
      <webElementGuid>0da40138-1002-480a-b411-91ae2468e424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::img[2]</value>
      <webElementGuid>7ce2c5d3-c314-409e-8040-08bdd78fb9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::img[2]</value>
      <webElementGuid>0ece49cb-e220-48c8-b6e0-390124cdb94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>7f8bf6c0-9d3f-42b2-9ab6-39cad1237fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>7931c13d-020b-4f12-a040-d2c65e179e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6IkNENENDN1pmaGhsVGtmeUh5S1ZtQlE9PSIsInZhbHVlIjoiVkFaSlA4VHhkTUR6QUFGNG1vNWNUcldwWEVGTEZjSlBVQ1R2OVVmL0s4TT0iLCJtYWMiOiJmOTVkMGYwZjY1NTUzNDQ0NGFiYjkzMzg3OThmYWU4YzJkMzc3ZGVjNmI3ZmE2Nzk0NDcxYTlhYTQyMTYxYjIzIiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>d5325497-a5ff-466c-a695-54a84c77ec53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
