<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5210deb7-f6d8-4100-b6b1-74388fdc0dc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d076578-613f-446c-89cb-881739514fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6InBXTW5FeWpDTlAxYkQvVVlHcVJ5Z0E9PSIsInZhbHVlIjoiWTdZREc5Z2tEb3BYWGhqWHh5cTR4NVNEMlUzY2x2MEVsV1AyYWZKYlh4ST0iLCJtYWMiOiI1OTNhNGI4MjY3NTYwNDFiZTRiNGUxZjlkMmI4YjA0MjUyNGMzNDg1NzY0NjYwNzBmNzE4OGI2MWUzY2I4M2Q5IiwidGFnIjoiIn0=</value>
      <webElementGuid>7b7fe778-7236-4ef2-8ef9-f5c776d882c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f3fd0342-17f9-45dd-b4a4-2edc76328cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>e730a9c6-afaa-477c-a052-af6687a6e3fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>38e1ad9b-4850-4c10-a6b2-6752447baf4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='has been successfully deleted'])[8]/following::img[1]</value>
      <webElementGuid>6acf573b-8fcc-4899-beef-779a807ea65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='videoplayback1'])[10]/following::img[1]</value>
      <webElementGuid>5d7ab515-01b0-4b59-9996-5a892a215cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::img[2]</value>
      <webElementGuid>4fcd5aaf-bed1-46e0-83ce-248df65aec97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::img[2]</value>
      <webElementGuid>6c5b5b57-4736-4415-8196-562462928d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>3b9fe872-a991-488f-84fb-8f690d0d3a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>b728e434-d4e5-4509-8842-c59b1448fef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6InBXTW5FeWpDTlAxYkQvVVlHcVJ5Z0E9PSIsInZhbHVlIjoiWTdZREc5Z2tEb3BYWGhqWHh5cTR4NVNEMlUzY2x2MEVsV1AyYWZKYlh4ST0iLCJtYWMiOiI1OTNhNGI4MjY3NTYwNDFiZTRiNGUxZjlkMmI4YjA0MjUyNGMzNDg1NzY0NjYwNzBmNzE4OGI2MWUzY2I4M2Q5IiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>bd734acf-433c-4e23-8eb0-595f527787db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
