<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3e520638-c5db-4e35-b005-28b18da739d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0c31e532-e1be-44c8-a2f6-7fcdb3d763fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6Imc5TTJMZ011a1N3Y21BY0hGVzFKSWc9PSIsInZhbHVlIjoiYnhGSDJ0SWY1cndSNlpWWkYwSVhJQzlXUkQrN3I3bG55N094L2V5Tjd2MD0iLCJtYWMiOiI4OTYwZTllZTAzMWYyNWUwOTBkODkyYzA4OWE3MWI0OTNmNTg5YThmNzhhYTc5MTBkMDU0ZjM5ODU1NjQ0MmNkIiwidGFnIjoiIn0=</value>
      <webElementGuid>245dc1b9-8703-4327-94f4-37338a90832b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32c8896e-b8c4-4dac-9b5b-294cafe36652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>69eefa47-5673-4422-bc98-2c6f0031b7e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>23cb27b5-e6b4-47cb-a66b-c4b5239a1ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='has been successfully updated'])[1]/following::img[1]</value>
      <webElementGuid>a76630af-a9d1-45bd-b111-767edcf1a64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='videoplayback'])[2]/following::img[1]</value>
      <webElementGuid>8b3c0666-fac7-49bf-b7b6-218549078af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::img[2]</value>
      <webElementGuid>084c5d27-b90d-46f1-bd73-985af9f67b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::img[2]</value>
      <webElementGuid>da846f10-f3a4-45bf-addd-87996473b321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>af3f1e1b-5e36-47c4-bc9a-989d4f2e501b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>01013038-5919-4ae4-92e6-38f0a2406739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6Imc5TTJMZ011a1N3Y21BY0hGVzFKSWc9PSIsInZhbHVlIjoiYnhGSDJ0SWY1cndSNlpWWkYwSVhJQzlXUkQrN3I3bG55N094L2V5Tjd2MD0iLCJtYWMiOiI4OTYwZTllZTAzMWYyNWUwOTBkODkyYzA4OWE3MWI0OTNmNTg5YThmNzhhYTc5MTBkMDU0ZjM5ODU1NjQ0MmNkIiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>d2bfe0b8-434b-4853-8e77-d4b3939a78e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
