<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>11a98e7a-acd0-41d2-820f-7e4eeeb5cea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>103aa2d0-9c14-405b-8372-19bdc6766251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6InJHakN5TmdWQThkT0QyMDdXNWw0emc9PSIsInZhbHVlIjoiVWVwQmRqK0piVitnTTZ4TjVYK00zTXNCYVgyWWJ4MzZzZXlzWjVjc09YOD0iLCJtYWMiOiJlYjQ5NTJiZDliNGEwODBiNzUxMGNhYjQxNDI1NzZkZmRhZjBjNGQxMzMxZmYzNzE3MTQ3MDk3ODA2Yjg3NmY1IiwidGFnIjoiIn0=</value>
      <webElementGuid>0f725740-e9d8-45d9-bd73-f680d2c6999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67cf284c-cd9e-484a-a84a-13f38ecb47e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>85b01a86-1041-4042-86f8-a36379a72703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>038f3afc-b520-4044-b099-76b645aba66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='has been successfully updated'])[1]/following::img[1]</value>
      <webElementGuid>a8e31389-0027-4713-a5c4-65efcfb721b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='videoplayback'])[2]/following::img[1]</value>
      <webElementGuid>34f8cb75-6457-4445-b0eb-4fefb8836a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::img[2]</value>
      <webElementGuid>2eadb24a-8eca-4493-9470-37a061a780b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::img[2]</value>
      <webElementGuid>a34d6c03-c2b2-48e4-a215-c7c8f23506a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>deafefbd-cf48-4282-8be8-3e9ddedf4733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>2244be6b-0eb6-455e-ae64-f2198056668a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6InJHakN5TmdWQThkT0QyMDdXNWw0emc9PSIsInZhbHVlIjoiVWVwQmRqK0piVitnTTZ4TjVYK00zTXNCYVgyWWJ4MzZzZXlzWjVjc09YOD0iLCJtYWMiOiJlYjQ5NTJiZDliNGEwODBiNzUxMGNhYjQxNDI1NzZkZmRhZjBjNGQxMzMxZmYzNzE3MTQ3MDk3ODA2Yjg3NmY1IiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>e27ae3c9-0312-4cbe-bed2-b2346f8008e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
