<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6b9a24fb-3f08-435a-87ca-90e5365bc4de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b029024f-5a54-4a1c-adf1-073aa7941ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6IjFjZ3FuR1hOSnFpTnFMRkM3bTNvbHc9PSIsInZhbHVlIjoiYUVXME5XeDNhT1JzRHJsN2hHRDhQc0QvYjBVT3hKMU5hRXF0Z3lUV1ZIcz0iLCJtYWMiOiJlNGFjZWYxYzUxYmUxNGQ0YzQ0ZTM0NDY4NGExMDk5MDMyYTQzMGMzZWE2YTQxMzUyZjU5NDYzNTMxYjkxN2IyIiwidGFnIjoiIn0=</value>
      <webElementGuid>0fa0ea26-8c67-4989-b15f-ce459acaefb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>be66ed32-b059-48c4-b6cc-95ab0415c93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>59f39a4c-065a-43fb-8db7-b201b19e5b60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>f75c8aa7-a8e1-4d9a-aa5b-13a931c811fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='has been successfully updated'])[1]/following::img[1]</value>
      <webElementGuid>632aff6c-b9f0-4248-9f5d-469c1194a2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='videoplayback'])[2]/following::img[1]</value>
      <webElementGuid>07b275ee-7b7d-4bd4-85e6-d74630a754ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::img[2]</value>
      <webElementGuid>2ceac581-0eef-4487-882a-6450d5900d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/preceding::img[2]</value>
      <webElementGuid>f85cf8a2-d5c7-4013-9412-d798384fd34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>86aec14d-672a-478c-bcec-b7e4771ecc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>2c6f25cf-edc5-449b-abd3-9ee21159e0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6IjFjZ3FuR1hOSnFpTnFMRkM3bTNvbHc9PSIsInZhbHVlIjoiYUVXME5XeDNhT1JzRHJsN2hHRDhQc0QvYjBVT3hKMU5hRXF0Z3lUV1ZIcz0iLCJtYWMiOiJlNGFjZWYxYzUxYmUxNGQ0YzQ0ZTM0NDY4NGExMDk5MDMyYTQzMGMzZWE2YTQxMzUyZjU5NDYzNTMxYjkxN2IyIiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>5c7a844f-62ee-43df-802c-bba79c41e7ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
