<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OnlineOffline Status_YCheckbox-input _407d75</name>
   <tag></tag>
   <elementGuidId>e90df2b1-c470-4c20-b392-1c18e7e499d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.head > div.YCheckbox.YCheckBox-root.YCheckBox-normal.YCheckBox-normalSecondary.YCheckBox-sizeSm.YCheckBox-normalSizeSm.css-1e0lep4 > label.YCheckbox-label.YCheckBox-label > div.YCheckbox-group > input.YCheckbox-input.YCheckBox-input.YCheckBox-inputSizeSm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6250587-dbb8-493f-bc46-3a0e11516945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2988f7c2-b395-49b5-b1cf-d690bf3f40ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>YCheckbox-input YCheckBox-input YCheckBox-inputSizeSm</value>
      <webElementGuid>8cca0b42-1335-400a-9601-71e9d01879f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-wm15xb&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root container-content css-87s48d&quot;]/div[@class=&quot;YBox-root css-87s48d&quot;]/div[@class=&quot;YBox-root css-87s48d&quot;]/div[@class=&quot;media css-11lrtib&quot;]/div[@class=&quot;YBox-root media-box css-87s48d&quot;]/div[@class=&quot;overlay&quot;]/div[@class=&quot;head&quot;]/div[@class=&quot;YCheckbox YCheckBox-root YCheckBox-normal YCheckBox-normalSecondary YCheckBox-sizeSm YCheckBox-normalSizeSm css-1e0lep4&quot;]/label[@class=&quot;YCheckbox-label YCheckBox-label&quot;]/div[@class=&quot;YCheckbox-group&quot;]/input[@class=&quot;YCheckbox-input YCheckBox-input YCheckBox-inputSizeSm&quot;]</value>
      <webElementGuid>bacb684d-0ba3-4507-bafb-38508e157bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[5]</value>
      <webElementGuid>28aff525-8ec1-4ce4-8806-b4529b812093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/div/div[2]/div/div/label/div/input</value>
      <webElementGuid>d9e796a0-70dd-4bd1-875a-208592a060ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/label/div/input</value>
      <webElementGuid>2f8939ab-c603-4b13-92ba-c63e60acaabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c8053a27-e864-4091-ab6c-2579ac6e2705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
