<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>faef2ab5-279b-43a3-b61a-286a615194b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>81736aa9-6033-40f4-9da9-0f0e55ce01f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6Ikttd21DVFVhdjAvdzltdEI1ZVgvZFE9PSIsInZhbHVlIjoicE1xK0RsS2RqV25TK2xBU2g5TWVIM3VnUWlORlNlQldGdzdHeHpzTFBPbz0iLCJtYWMiOiJkMjE4ZDc3OWM3NzZjYzY2MDNmMDgyMjUyOTIxOGNlOGY1MWRhZDAxMTc3OWEzNzExMmNkMmQwNjI1YTAwOGI5IiwidGFnIjoiIn0=</value>
      <webElementGuid>d35b2110-81a2-4fb3-83c0-d9e0b639c274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0c00da2-89c3-4a66-8cf7-b4e512f453ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;css-1d5zm2c&quot;]/div[@class=&quot;layout-main desktop&quot;]/div[@class=&quot;css-twkkja&quot;]/div[@class=&quot;YBox-root container css-87s48d&quot;]/div[@class=&quot;YBox-root right css-87s48d&quot;]/div[@class=&quot;setting css-19ivad1&quot;]/button[@class=&quot;YIconButton-root setting-button css-120lm04&quot;]/img[1]</value>
      <webElementGuid>1bb92333-6a16-443e-8e73-58d5eb5b4674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div[2]/div[2]/div[2]/button/img</value>
      <webElementGuid>8acea16b-a4cd-4b15-bc4a-6922f9ca88d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='img']</value>
      <webElementGuid>e0b24323-688d-4b44-9581-f6033904a400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>f166c903-de8f-4fea-9cad-6bd62e8c7f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.staging-pixelpop.inovasi.top/locate/media/eyJpdiI6Ikttd21DVFVhdjAvdzltdEI1ZVgvZFE9PSIsInZhbHVlIjoicE1xK0RsS2RqV25TK2xBU2g5TWVIM3VnUWlORlNlQldGdzdHeHpzTFBPbz0iLCJtYWMiOiJkMjE4ZDc3OWM3NzZjYzY2MDNmMDgyMjUyOTIxOGNlOGY1MWRhZDAxMTc3OWEzNzExMmNkMmQwNjI1YTAwOGI5IiwidGFnIjoiIn0=' and @alt = 'img']</value>
      <webElementGuid>3c8f25eb-caf4-4e9b-8209-b88192148b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
